// Company slug redirects (P6-01, ADR-0006): an old company slug keeps working by redirecting to the current page.
// The static host reads them from public/_redirects (Workers static assets), so the build writes one rule per old
// slug for the company page and one for its jobs page. Pure functions, unit-tested.

export type SlugRedirect = { old_slug: string; new_slug: string };

/** What one city's snapshot says: its redirects, and the slugs its companies use today. */
export type CityRedirects = { city: string; redirects: readonly SlugRedirect[]; currentSlugs: readonly string[] };

const MAX_CHAIN = 10;

/**
 * Merges the redirects of every city into one list, sorted by old slug. A company in two cities appears in both
 * snapshots, so identical rules are one. Throws (failing the build) when the data cannot be served:
 *  - an old slug that a company uses today (the redirect would hide that company's page);
 *  - an old slug that points at two different slugs;
 *  - a redirect to itself, or a loop.
 * A chain (old to older to current) is flattened: every old slug points straight at the final page.
 */
export function collectRedirects(cities: readonly CityRedirects[]): SlugRedirect[] {
  const current = new Set(cities.flatMap((c) => c.currentSlugs));
  const target = new Map<string, string>();
  for (const { city, redirects } of cities) {
    for (const r of redirects) {
      if (r.old_slug === r.new_slug) throw new Error(`${city}: the slug ${r.old_slug} redirects to itself`);
      if (current.has(r.old_slug)) throw new Error(`${city}: the slug ${r.old_slug} redirects elsewhere but a company uses it today`);
      const existing = target.get(r.old_slug);
      if (existing !== undefined && existing !== r.new_slug) {
        throw new Error(`${city}: the slug ${r.old_slug} redirects to both ${existing} and ${r.new_slug}`);
      }
      target.set(r.old_slug, r.new_slug);
    }
  }

  const resolve = (slug: string): string => {
    let at = slug;
    for (let i = 0; i < MAX_CHAIN; i++) {
      const next = target.get(at);
      if (next === undefined) return at;
      at = next;
    }
    throw new Error(`The redirects from ${slug} loop or chain more than ${MAX_CHAIN} times`);
  };

  return [...target.keys()]
    .sort()
    .map((old) => ({ old_slug: old, new_slug: resolve(old) }))
    .map((r) => {
      if (!current.has(r.new_slug)) throw new Error(`The slug ${r.old_slug} redirects to ${r.new_slug}, which no company uses`);
      return r;
    });
}

/** The text of public/_redirects: the static rules, then two generated rules per old slug. */
export function renderRedirects(staticRules: string, redirects: readonly SlugRedirect[]): string {
  const lines = [staticRules.trimEnd(), "", "# Company slug redirects, generated by `npm run data` from the database (P6-01). Do not edit."];
  for (const r of redirects) {
    lines.push(`/companies/${r.old_slug} /companies/${r.new_slug} 301`);
    lines.push(`/companies/${r.old_slug}/jobs /companies/${r.new_slug}/jobs 301`);
  }
  return lines.join("\n") + "\n";
}
